package:
  format-version: "1.0.0"
  name: "smartenergy_prime"
  version: "v1.0.0"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy"
      type: "package"
      version: "1.4.1"
    - name: "crypto_v4"
      type: "package"
      version: "v4.0.0-E3"