package:
  format-version: "1.0.0"
  name: "smartenergy_prime"
  version: "v1.0.0"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy"
      type: "package"
      version: "dev"
    - name: "crypto_v4"
      type: "package"
      version: "master"
