package:
  format-version: "1.0.0"
  name: "smartenergy_prime"
  version: "v1.0.0"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy"
      type: "package"
      version: "dev"
    - name: "core"
      type: "package"
      version: "v3.14.0"
    - name: "crypto"
      type: "package"
      version: "v4.0.0-E3"