package:
  format-version: "1.0.0"
  name: "smartenergy_prime"
  version: "v1.0.0"
  type: "api"
  status: "production"
  required: true

  dependencies:
    - name: "smartenergy"
      type: "package"
      version: "v1.0.0"
